### ISSUE TITLE
Error on building mapper

### ISSUE THREAD

**Issue by borsna** [TheLanguageArchive/md-mapper#2]
When builing application I got:

```
[olof@k2 md-mapper]$ mvn clean package assembly:assembly
---------------------------------------------------
constituent[0]: file:/usr/share/maven/lib/maven-wagon_http-shaded.jar
constituent[1]: file:/usr/share/maven/lib/plexus_containers-component-annotation                                                   s.jar
constituent[2]: file:/usr/share/maven/lib/cdi-apicdi-api.jar
constituent[3]: file:/usr/share/maven/lib/maven-model-builder.jar
constituent[4]: file:/usr/share/maven/lib/aether_aether-api.jar
constituent[5]: file:/usr/share/maven/lib/httpcomponents_httpcore.jar
constituent[6]: file:/usr/share/maven/lib/atinject.jar
constituent[7]: file:/usr/share/maven/lib/commons-logging.jar
constituent[8]: file:/usr/share/maven/lib/aopalliance.jar
constituent[9]: file:/usr/share/maven/lib/maven-settings-builder.jar
constituent[10]: file:/usr/share/maven/lib/maven-wagon_provider-api.jar
constituent[11]: file:/usr/share/maven/lib/org.eclipse.sisu.plexus.jar
constituent[12]: file:/usr/share/maven/lib/maven-compat.jar
constituent[13]: file:/usr/share/maven/lib/jsr-305.jar
constituent[14]: file:/usr/share/maven/lib/aether_aether-impl.jar
constituent[15]: file:/usr/share/maven/lib/slf4j_api.jar
constituent[16]: file:/usr/share/maven/lib/google-guice-no_aop.jar
constituent[17]: file:/usr/share/maven/lib/commons-codec.jar
constituent[18]: file:/usr/share/maven/lib/plexus_plexus-cipher.jar
constituent[19]: file:/usr/share/maven/lib/maven-repository-metadata.jar
constituent[20]: file:/usr/share/maven/lib/maven-wagon_http-shared4.jar
constituent[21]: file:/usr/share/maven/lib/plexus_plexus-sec-dispatcher.jar
constituent[22]: file:/usr/share/maven/lib/geronimo-annotation.jar
constituent[23]: file:/usr/share/maven/lib/maven-artifact.jar
constituent[24]: file:/usr/share/maven/lib/maven-core.jar
constituent[25]: file:/usr/share/maven/lib/slf4j_simple.jar
constituent[26]: file:/usr/share/maven/lib/commons-cli.jar
constituent[27]: file:/usr/share/maven/lib/aether_aether-transport-wagon.jar
constituent[28]: file:/usr/share/maven/lib/plexus_interpolation.jar
constituent[29]: file:/usr/share/maven/lib/maven-settings.jar
constituent[30]: file:/usr/share/maven/lib/maven-wagon_file.jar
constituent[31]: file:/usr/share/maven/lib/maven-aether-provider.jar
constituent[32]: file:/usr/share/maven/lib/aether_aether-spi.jar
constituent[33]: file:/usr/share/maven/lib/httpcomponents_httpclient.jar
constituent[34]: file:/usr/share/maven/lib/org.eclipse.sisu.inject.jar
constituent[35]: file:/usr/share/maven/lib/aether_aether-connector-basic.jar
constituent[36]: file:/usr/share/maven/lib/maven-model.jar
constituent[37]: file:/usr/share/maven/lib/maven-plugin-api.jar
constituent[38]: file:/usr/share/maven/lib/aether_aether-util.jar
constituent[39]: file:/usr/share/maven/lib/guava.jar
constituent[40]: file:/usr/share/maven/lib/maven-embedder.jar
constituent[41]: file:/usr/share/maven/lib/plexus_utils.jar
constituent[42]: file:/usr/share/maven/conf/logging/
---------------------------------------------------
Exception in thread "main" java.lang.UnsupportedClassVersionError: javax/inject/                                                   Provider : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:14                                                   1)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(Cl                                                   assRealm.java:389)
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(                                                   SelfFirstStrategy.java:42)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadCl                                                   ass(ClassRealm.java:259)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm                                                   .java:242)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm                                                   .java:227)
        at org.apache.maven.cli.MavenCli.container(MavenCli.java:401)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:208)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.                                                   java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                   sorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun                                                   cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav                                                   a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La                                                   uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:                                                   356)
```

Version of javac:
javac 1.7.0_55

**Comment by larilampen** [comment]
Hi Olof (and other watchers). I've left TLA behind, but I haven't unwatched this project, so I happened to notice this ticket. I think I know the problem: you have a JRE of version < 1.7 in your path before the JDK. Check version of java instead of javac. To fix, change your path (if you're on Ubuntu or other Debian derivative, use update-alternatives).

**Comment by borsna** [comment]
Thank you for your response Lari.
I am running 1.7 JRE:

```
[olof@k2 ~]$ java -version
java version "1.7.0_55"
OpenJDK Runtime Environment (fedora-2.4.7.4.fc20-x86_64 u55-b13)
OpenJDK 64-Bit Server VM (build 24.51-b03, mixed mode)
```

Can someone still at TLA help with this issue?

Please keep the issue open until resolved.

Best regards,
Olof

**Comment by larilampen** [comment]
OK, my bad, I'll reopen this and leave it for someone else to look at. I still think there's another JRE involved (perhaps via $JAVA_HOME), since 1.7 should never produce that error.

**Comment by borsna** [comment]
fedora seams to have java-6 set as default home.
Added this to .bashrc and got it to work:

```
export JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk
```

**Comment by kjvandelooij** [comment]
Dear Olof,

from the output you posted, I cannot determine if you indeed installed the mapper from the package created, or that it is that case that you cannot build the package. It might not apply to your configuration (I am running Ubuntu), but with

  sudo update-alternatives --config javax

  There are 3 choices for the alternative java (providing /usr/bin/java).

```
Selection    Path                       Priority   Status
```

---

```
0            /usr/bin/gij-4.6            1046      auto mode
1            /opt/jdk1.6.0_45/bin/java   1         manual mode
```
- 2            /opt/jdk1.7.0_45/bin/java   1         manual mode
  3            /usr/bin/gij-4.6            1046      manual mode

and

  echo $JAVA_HOME
  /opt/jdk1.7.0_45/

I have no difficulty building the package. I remember that I once had an issue getting the mapper to run because I tried to run it from the archive directly instead of the package. In other words: you need to run the script. Also, you might try to run the mapper from within an IDE, that might give you some additional information - if that is not already the case.

Please let me know how things turn out.

Best wishes, kj

On Mon, 4 Aug 2014 13:59:07 +0200
Olof Olsson notifications@github.com wrote:

> When builing application I got:[olof@k2 md-mapper]$ mvn clean package
> assembly:assembly ---------------------------------------------------
> constituent[0]: file:/usr/share/maven/lib/maven-wagon_http-shaded.jar
> constituent[1]:
> file:/usr/share/maven/lib/plexus_containers-component-annotation
> s.jar constituent[2]: file:/usr/share/maven/lib/cdi-apicdi-api.jar
> constituent[3]: file:/usr/share/maven/lib/maven-model-builder.jar
> constituent[4]: file:/usr/share/maven/lib/aether_aether-api.jar
> constituent[5]: file:/usr/share/maven/lib/httpcomponents_httpcore.jar
> constituent[6]: file:/usr/share/maven/lib/atinject.jar
> constituent[7]: file:/usr/share/maven/lib/commons-logging.jar
> constituent[8]: file:/usr/share/maven/lib/aopalliance.jar
> constituent[9]: file:/usr/share/maven/lib/maven-settings-builder.jar
> constituent[10]:
> file:/usr/share/maven/lib/maven-wagon_provider-api.jar
> constituent[11]:
> file:/usr/share/maven/lib/org.eclipse.sisu.plexus.jar
> constituent[12]: file:/usr/share/maven/lib/maven-compat.jar
> constituent[13]: file:/usr/share/maven/lib/jsr-305.jar
> constituent[14]: file:/usr/share/maven/lib/aether_aether-impl.jar
> constituent[15]: file:/usr/share/maven/lib/slf4j_api.jar
> constituent[16]: file:/usr/share/maven/lib/google-guice-no_aop.jar
> constituent[17]: file:/usr/share/maven/lib/commons-codec.jar
> constituent[18]: file:/usr/share/maven/lib/plexus_plexus-cipher.jar
> constituent[19]:
> file:/usr/share/maven/lib/maven-repository-metadata.jar
> constituent[20]:
> file:/usr/share/maven/lib/maven-wagon_http-shared4.jar
> constituent[21]:
> file:/usr/share/maven/lib/plexus_plexus-sec-dispatcher.jar
> constituent[22]: file:/usr/share/maven/lib/geronimo-annotation.jar
> constituent[23]: file:/usr/share/maven/lib/maven-artifact.jar
> constituent[24]: file:/usr/share/maven/lib/maven-core.jar
> constituent[25]: file:/usr/share/maven/lib/slf4j_simple.jar
> constituent[26]: file:/usr/share/maven/lib/commons-cli.jar
> constituent[27]:
> file:/usr/share/maven/lib/aether_aether-transport-wagon.jar
> constituent[28]: file:/usr/share/maven/lib/plexus_interpolation.jar
> constituent[29]: file:/usr/share/maven/lib/maven-settings.jar
> constituent[30]: file:/usr/share/maven/lib/maven-wagon_file.jar
> constituent[31]: file:/usr/share/maven/lib/maven-aether-provider.jar
> constituent[32]: file:/usr/share/maven/lib/aether_aether-spi.jar
> constituent[33]:
> file:/usr/share/maven/lib/httpcomponents_httpclient.jar
> constituent[34]:
> file:/usr/share/maven/lib/org.eclipse.sisu.inject.jar
> constituent[35]:
> file:/usr/share/maven/lib/aether_aether-connector-basic.jar
> constituent[36]: file:/usr/share/maven/lib/maven-model.jar
> constituent[37]: file:/usr/share/maven/lib/maven-plugin-api.jar
> constituent[38]: file:/usr/share/maven/lib/aether_aether-util.jar
> constituent[39]: file:/usr/share/maven/lib/guava.jar constituent[40]:
> file:/usr/share/maven/lib/maven-embedder.jar constituent[41]:
> file:/usr/share/maven/lib/plexus_utils.jar constituent[42]:
> file:/usr/share/maven/conf/logging/
> --------------------------------------------------- Exception in
> thread "main" java.lang.UnsupportedClassVersionError:
> javax/inject/
> Provider : Unsupported major.minor version 51.0 at
> java.lang.ClassLoader.defineClass1(Native Method) at
> java.lang.ClassLoader.defineClassCond(ClassLoader.java:631) at
> java.lang.ClassLoader.defineClass(ClassLoader.java:615) at
> java.security.SecureClassLoader.defineClass(SecureClassLoader.java:14
> 1) at java.net.URLClassLoader.defineClass(URLClassLoader.java:283) at
> java.net.URLClassLoader.access$000(URLClassLoader.java:58) at
> java.net.URLClassLoader$1.run(URLClassLoader.java:197) at
> java.security.AccessController.doPrivileged(Native Method) at
> java.net.URLClassLoader.findClass(URLClassLoader.java:190) at
> org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(Cl
> assRealm.java:389) at
> org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(                                                   SelfFirstStrategy.java:42)
> at
> org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadCl
> ass(ClassRealm.java:259) at
> org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm                                                   .java:242)
> at
> org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm                                                   .java:227)
> at org.apache.maven.cli.MavenCli.container(MavenCli.java:401) at
> org.apache.maven.cli.MavenCli.doMain(MavenCli.java:208) at
> org.apache.maven.cli.MavenCli.main(MavenCli.java:158) at
> sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at
> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
> java:39) at
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
> sorImpl.java:25) at java.lang.reflect.Method.invoke(Method.java:597)
> at
> org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
> cher.java:289) at
> org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
> a:229) at
> org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
> uncher.java:415) at
> org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
> 356)
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Kees Jan van de Looij
Max Planck Institute for Psycholinguistics, Nijmegen, the Netherlands
tel. +31-(0)24-3521-478 | http://www.mpi.nl/

**Comment by borsna** [comment]
Hi Kees Jan,
I am not sure what you mean by installing the package?
The build was successful after i updated `$JAVA_HOME`
As i mention i #3 there is an error when running the jar-file witch seams to be related in some bug where the lib log4j is not included in the right way. Could this be something witch is globaly defined as a lib on you system?
Can you check if this in linked in the correct way in the source? (i´m not a java developer)

Best regards,
Olof

**Comment by kjvandelooij** [comment]
Hi Olof, 

ok, I understand. I was not aware of the fact that you do not develop Java. Well, as a result of the mvn command, a package is build. This package takes the form of a .tar.gz file. If you unpack this archive, you will get a directory tree that is intended as a context for the mapper to run in. There is even a script available to start the mapper. 

Hope this helps. 

Greetings, 

Kees Jan van de Looij
Max Planck Institute for Psycholinguistics, Nijmegen, the Netherlands
tel. +31-(0)24-3521-478 | http://www.mpi.nl/

**Comment by borsna** [comment]
Hi Kees Jan,
i unpacked the archive started the application via  `run-mapper.sh` however i got the same error message:

```
[olof@k2 md-mapper-0.1.a8ac39]$ ./run-mapper.sh config=/home/olof/5.4/config.xml
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Logger
        at nl.mpi.mdmapper.Main.<clinit>(Main.java:37)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 1 more
```

Should i send a copy of the build?
